### ISSUE TITLE
301 by getStatement

### ISSUE THREAD

**Issue by kitokirisaki** [netnexus/IKontist#1]
["url"]=> string(60) "https://api.kontist.com/api/accounts/{accountId}/statements/2017/11"
["redirect_url"]=> string(51) "https://api.kontist.com/api/user/statements/2017/11"

but if i change the url i get a 404. so maybe a PUT or POST is needed.

**Comment by johannespfeiffer** [comment]
Hi,
you are right.

(1) The endpoints url changed.
(2) There was a problem with the redirect to the statements storage:

`{ Code: 'InvalidArgument',
  Message: 'Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified', ... }`

Should be fixed.

Kind regards
Joe
