### ISSUE TITLE
 KontistClient is not a constructor

### ISSUE THREAD

**Issue by finnmeier23** [netnexus/IKontist#3]
I tried to get the api to work , but i get every time following Error: 

`TypeError: KontistClient is not a constructor`

Here is my Code i tried:

`const KontistClient = require("@netnexus/ikontist");
const client = new KontistClient();
client.login(process.env.KONTIST_USER, process.env.KONTIST_PASSWORD).then(function() {
    // do further calls to kontist here
})`

**Comment by johannespfeiffer** [comment]
Thank you, adjusted the docs.

It should be:
```ts
const ikontist = require("kontist-client");
const client = new ikontist.KontistClient();
client.login(process.env.KONTIST_USER, process.env.KONTIST_PASSWORD).then(function() {
    // do further calls to kontist here
})
```

or if you use ES6 import style:
```ts
import { KontistClient } from "@netnexus/ikontist";
const client = new KontistClient();
```
